---
language: ruby
bundler_args: --without development
script: bundle exec rake test
before_install: rm -f Gemfile.lock
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.5" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.5" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.5" STRICT_VARIABLES="yes"
notifications:
  email: false