---
sudo: required
language: ruby
services:
  - docker
install:
  - docker version
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install -y libaugeas-dev libxml2-dev
  - bundle install --without development
script: spec/scripts/run.sh
before_install: rm -f Gemfile.lock
matrix:
  fast_finish: true
  include:
  - rvm: '1.8'
    env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
  - rvm: '1.8'
    env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
  - rvm: '1.9'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.0'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - rvm: '2.1'
    env: PUPPET_VERSION="3.8.2" RS_SET="centos-65-x64-docker" 
  - rvm: '2.1'
    env: PUPPET_VERSION="3.8.2" RS_SET="ubuntu-server-1404-x64-docker"    
# Travis: Out of hdd space
#  - rvm: '2.1'
#    env: RS_SET="centos-65-x64-pe288-docker"
#  - rvm: '2.1'
#    env: RS_SET="centos-65-x64-pe382-docker"
notifications:
  email: false
