---
language: ruby
sudo: false
addons:
  apt:
    sources:
    - augeas
    packages:
    - libaugeas-dev
    - libxml2-dev
bundler_args: --without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
cache: bundler
script: bundle exec rake test
before_install: rm -f Gemfile.lock
matrix:
  fast_finish: true
  include:
  - rvm: '1.8'
    env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.6.0"
  - rvm: '1.8'
    env: PUPPET_VERSION="~> 2.7.0" FACTER_VERSION="~> 1.7.0"
  - rvm: '1.9'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.0'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3.0"
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.4" RS_SET="centos-6-x86_64-docker"
    script: bundle exec rake acceptance
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.4" RS_SET="debian-7-x86_64-docker"
    script: bundle exec rake acceptance
  - rvm: '2.1'
    sudo: required
    services: docker
    env: PUPPET_VERSION="3.8.4" RS_SET="ubuntu-14.04-x86_64-docker"
    script: bundle exec rake acceptance
  # FIXME: GH Issue #3 - Activate acceptance tests on Travis CI for Puppet Enterprise, at least 2.8.8 and 3.8.2
notifications:
  email: false
  slack:
    rooms:
      - $SLACK_TOKEN#ci
    on_success: always
    on_failure: always
    on_start: always
